### ISSUE TITLE
TODO - Game Loop

### ISSUE THREAD

**Issue by dee12452** [dee12452/PokemonElectricYellow#4]
Tasks:
- [x] Add delta time
- [x] Cap framerate to config file entry
- [ ] Add game states (pause, resume, etc.)
- [x] Create a Game Registry that will update tickable objects. Have Game Loop update Game Registry
